services:
  db:
    build: .
    container_name: draftgap_db
    restart: always
    command: --skip-name-resolve
    ports:
      - "3306:3306"
    environment:
      # Credentials for the database
      MYSQL_ROOT_PASSWORD: Alumno1*
      MYSQL_DATABASE: draftgap
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: devpassword
    volumes:
      # Persist data so you don't lose users/matches when restarting
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: draftgap_phpmyadmin
    restart: always
    ports:
      # Access phpMyAdmin at http://10.128.10.31:8080
      - "8080:80"
    environment:
      # Connects to the service named 'db' defined above
      PMA_HOST: db
      # Optional: Allows automatic login or simpler setup
      MYSQL_ROOT_PASSWORD: Alumno1*
    depends_on:
      - db

volumes:
  db_data: